name: emergency_res_loc_new
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^20.0.0
  flutterfire_cli: ^1.3.1
  fluttertoast: ^9.0.0
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  flutter_contacts_service: ^0.0.3
  permission_handler: ^12.0.1
  http: ^1.1.2
  url_launcher: ^6.2.6
  geocoding: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
    android: "ic_launcher"
    ios: true
    image_path: "assets/logo.jpg"
    min_sdk_android: 21 # android min sdk min:16, default 21







flutter:

  uses-material-design: true